# Generated by Django 4.1.2 on 2022-11-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="boardtag",
            name="board_id",
        ),
        migrations.RemoveField(
            model_name="boardtag",
            name="tag_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="mark",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="mark",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="board_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="written_user_id",
        ),
    ]
