# Generated by Django 4.1.3 on 2022-11-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_tag_boardtag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
