# Generated by Django 4.1.3 on 2022-12-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0006_board_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoardTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
